# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5964ba2374d8a8fe90a253847edb5b886993371385ba2a7cdcf5281ab4786042ecb4a7ccc72d06951055d4b1b2941d301b4dcb3b47ebc2bec66212e85dead768

test:
  secret_key_base: 8f0f13be7784763542cd1234c4d763415d29a8122a0a61b42491912c08b54131f58d08e1b4296a7083d82add4ddd27f2b46830b5e5614f3db8e16893a6661395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
